### ISSUE TITLE
Toma de Requerimientos

### ISSUE THREAD

**Issue by dynobro** [araucanosland/MDN-Microservices#1]
Las Etapas deben ser las siguientes

0. Prospección
1. **Tubo Comercial: Levantamiento o validación de datos => [Datos Válidos]**
**Si le interesa a la empresa**: se debe avanzar a la siguiente etapa
**Si NO le interesa a la empresa**: Muere el proceso, se debe indicar por que.

Opciones:
Todas las de contacto de motor
mas termionales acepta o no le interesa

2. Tubo Comercial: Gestion de Venta  => [Intención de Cambio de la Empresa]
<< 1st Sprint>>
3. Difusión y Promoción => [Intencion de Sufragios]

**Alcances**
- Se debe poder editar los contactos
- Se puede generar una agenda de compromisos de los Ejecutivos

***Definiciones Aqui***

La primera fase después que llegan los clasificados de riesgo, deberia ser una campaña para detectar cuales son las empresas realmente interesadas en cambiarse de caja

algo nuevo

**Comment by capradenas** [comment]
**Para los Prospectos**

agregar nombre del ejecutivo que cargo la información

opcion de calendario

Validacion de rut al ingresar empresa (si existe ya debe acusar).

opcion de otros en Contactos
